### ISSUE TITLE
Fails on /usr/bin

### ISSUE THREAD

**Issue by nickfierro** [saltstack-formulas/os-hardening-formula#19]
----------
          ID: hardening-read-only-folders
    Function: file.directory
        Name: /usr/bin
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3104, in directory
                  full, ret, user, group, file_mode, None, follow_symlinks)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4460, in check_perms
                  lattrs = lsattr(name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 564, in lsattr
                  raise SaltInvocationError("File or directory does not exist.")
              SaltInvocationError: File or directory does not exist.
     Started: 21:14:22.248613
    Duration: 2840.078 ms
     Changes:

**Comment by abednarik** [comment]
Hi

 Same issue here. In Ubuntu is because of this broken symlink

```
ls -l /usr/bin/vmware-user
lrwxrwxrwx 1 root root 24 May  8 16:51 /usr/bin/vmware-user -> vmware-user-suid-wrapper
```

**Comment by nickfierro** [comment]
<img width="725" alt="screen shot 2018-10-18 at 2 34 59 pm" src="https://user-images.githubusercontent.com/6640284/47176235-17974980-d2e3-11e8-83ee-02b6fdfb62fa.png">

It also appears to be a broken symlink on mine as well. It looks like vmware-user-suid-wrapper does not get installed or linked.
